# Generated by Django 3.0.8 on 2021-02-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='period',
            field=models.ManyToManyField(to='timezone.Period'),
        ),
    ]
